### ISSUE TITLE
0.5.0 breaks python 2 packages that did not pin 0.4.0

### ISSUE THREAD

**Issue by ThiefMaster** [claudep/translitcodec#3]
This could have avoided by using `python_requires` restricting the new version to 3.x versions.

Would you consider yanking 0.5.0 from PyPI and making a 0.5.1 release that explicitly specifies being incompatible with Python 2?

Of course pinning version would have been better, but with no release in 5 years I'm sure there are more packages out there which didn't do so, and are now required to make a new release just because of this...

**Comment by claudep** [comment]
Hopefully done now.

**Comment by ThiefMaster** [comment]
Hey, thanks a lot for the quick solution, but unfortunately it doesn't work. :/
I checked with the pypi/pip devs since I was surprised by this as well, and this is what they replied:

> Oh, I see the problem.
> He is using `setup.py upload`
> With presumably a very old version of `setuptools`.
> He needs to pull 0.5.1 and upload a new version using `twine`.
> ...
> You may also want to tell him to switch out the reference to `distutils` in `setup.py` with `setuptools`.
> If he had a recent version of `setuptools` `setup.py upload` would have raised an error.

**Comment by claudep** [comment]
I didn't upload with `setup.py`, I used `twine 3.1.1`. I'll see with replacing `distutils`, but I probably won't upload a new version. If you still have Python 2 code, please pin to 0.4.

**Comment by ThiefMaster** [comment]
The problem isn't so much pinning it (I should have done that a long time ago when adding the dependency) but being forced to make new releases for all supported versions (which, while of course possible, is a hassle) or telling people to manually install the older version first.

Looking at the [dependents](https://github.com/claudep/translitcodec/network/dependents?dependent_type=PACKAGE) there's at least [one other](https://github.com/LeetCode-OpenSource/django-autoslug/blob/master/setup.py#L28-L32) package that would also pull in an incompatible version on 2.7...

**Comment by claudep** [comment]
Frankly, I still don't understand what is wrong with the 0.5.1 package.

BTW, Python 2 is dying, don't you have a Python 3 upgrade plan?

**Comment by ThiefMaster** [comment]
> Frankly, I still don't understand what is wrong with the 0.5.1 package.

Basically, for some reason (maybe the fact that distutils instead of setuptools was used) the "requires-python" metadata was not included in the upload. You can compare e.g. https://pypi.org/project/translitcodec/0.5.1/ vs https://pypi.org/project/python-dateutil/; the latter shows "Requires: Python !=3.0.*, !=3.1.*, !=3.2.*, >=2.7" on the sidebar indicating the restrictions pip will take into account.

> BTW, Python 2 is dying, don't you have a Python 3 upgrade plan?

Of course we do ("this year"), but for a bigger project it takes time and in the meantime it's annoying for people not being able to install the existing release.

**Comment by claudep** [comment]
So I republished with the distutils vs setuptools replacement. Hopefully...

**Comment by ThiefMaster** [comment]
works fine now, thanks a lot!

**Comment by claudep** [comment]
You are welcome, and if you need it, I have some practice in upgrading to Python 3!
