### ISSUE TITLE
Failure to transliterate the ß character in the translit/short codec

### ISSUE THREAD

**Issue by FortisJoe** [claudep/translitcodec#5]
Hello,

I am having problems when trying to transliterate the ß character in the translit/short codec, and I think the issue also continues in translit/one

short should translit to "ss"
one should translit to "s"

Code example:

`codecs.encode("ß", "translit/short")`
Returns 'β'

Lines which I believe contain the fix

https://github.com/claudep/translitcodec/blob/7bc854f65b1bc53854a1a09ffb0c2974288faa6e/translitcodec/__init__.py#L1026
https://github.com/claudep/translitcodec/blob/7bc854f65b1bc53854a1a09ffb0c2974288faa6e/translitcodec/__init__.py#L1864

**Comment by claudep** [comment]
Would you like to provide a patch?

**Comment by FortisJoe** [comment]
Sure, please see attached.
[Fix_transliteration.zip](https://github.com/claudep/translitcodec/files/5874577/Fix_transliteration.zip)
